services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
  backend:
    image: ruby:3.0.2
    volumes:
      - ./backend:/backend
      - rubygems:/usr/local/bundle
    working_dir: /backend
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
    depends_on:
      - db
    ports:
      - 3000:3000
    command: bash -c "rm tmp/pids/server.pid & bin/setup & rails server -b 0.0.0.0"
  frontend:
    image: node
    depends_on:
      - backend
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    ports:
      - 5173:5173
    command: bash -c "yarn dev --host"
# Ao inves de usar o create-react-app no frontend usou o create vite --template react .
volumes:
  rubygems: {}
